apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server
data:
  # property-like keys; each key maps to a simple value
  CONFIG_SERVER_URL: "http://config-server:8888"
  APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=6411b220-532f-462e-9d8d-6513ba566170;IngestionEndpoint=https://eastus2-3.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus2.livediagnostics.monitor.azure.com/;ApplicationId=af15194f-99e4-4e4f-89be-d1b8c04f0484"
